apiVersion: v1
kind: Namespace
metadata:
  name: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: image-urls
  namespace: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
data:
  dummy: FILLED_IN_BY_CI
