version: "3.2"
services:
  remoter-server:
    container_name: "biomage-remoter-server"
    image: "biomage-remoter-server"
    build:
      context: remoter-server/
      target: dev
      args:
        - GITHUB_PAT=${GITHUB_PAT}
    volumes:
      - ./remoter-server:/remoter-server:cached
      - ~/.aws:/root/.aws:cached
      - ./remoter-client/src:/remoter-server/client-scripts:cached
    ports:
      - "6969:6969"
